sonar.projectKey=student-task-api
sonar.projectName=Student Task API
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**
sonar.sourceEncoding=UTF-8